---
abstract: 'Perl extension for writing XML'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Slurp: 0
  Test::Exception: 0
  Test::Memory::Cycle: 0
  Test::More: '0.42'
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-API
no_index:
  directory:
    - example
    - inc
    - t
  package:
    - XML::API::Element
    - XML::API::SAXHandler
requires:
  Scalar::Util: 0
  XML::LibXML::SAX: 0
  XML::SAX: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=XML-API
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/mlawren/xml-api.git
version: '0.28'
